add clean back

diff --git a/.github/workflows/BLE_Examples_Test.yml b/.github/workflows/BLE_Examples_Test.yml
--- a/.github/workflows/BLE_Examples_Test.yml
+++ b/.github/workflows/BLE_Examples_Test.yml
@@ -28,14 +28,10 @@ on:
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
-env:
-  TEST_MAX32655: false
-  TEST_MAX32665: false
-  TEST_MAX32690: false
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  TEST_BLE_Devices:
+  build:
     # The type of runner that the job will run on
     runs-on: [self-hosted, btm-ci]
     if: github.event.pull_request.draft == false
@@ -43,15 +39,23 @@ jobs:
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Clean and remove any local modifications
-      # - name: Clean
-      #   continue-on-error: true
-      #   run: |
-      #     # Remove local modifications
-      #     set +e
+      - name: Clean
+        continue-on-error: true
+        run: |
+          # Remove local modifications
+          set +e
 
-      #     # Attempt to clean the repo
+          # Attempt to clean the repo
+          git scorch
+          retval=$?
 
-      #     set -e
+          # Remove everything if this fails
+          if [[ $retval -ne 0 ]]
+          then
+            rm -rf *
+          fi
+
+          set -e
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
         with:
@@ -62,14 +66,21 @@ jobs:
       # even if only one board is being tested. This is so that another job
       # does not possibly used one of the free boards that may connect to the
       #current board undertest
+      - name: Lock All Boards
+        if: ${{ always() }}
+        id: lock_files
+        run: |
+          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32655_board1
+          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32655_board2
+          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32665_board1
+          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32690_board_w1
 
       # ME17
-      - name: Check MAX32655 #name used for display purposes on github webpage
-        id: MAX32655 #id used to reference this step in other parts of the yml
+      - name: TEST MAX32655
         run: |
 
           # Remove local modifications
-          #git scorch
+          git scorch
 
           BLE_FILES_CHANGED=0
           RUN_TEST=0
@@ -117,18 +128,24 @@ jobs:
           # Assume we want to actually run the workflow if no files changed
             RUN_TEST=1
           fi
-          # save result to steps output
+
           if [[ $RUN_TEST -eq 1 ]]
           then
-            echo "TEST_MAX32655=true" >> $GITHUB_ENV
+            echo "Running Test"
+
+            cd .github/workflows/scripts
+            chmod +x test_launcher.sh
+            FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
+            dut_uart=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32655_board2']['uart0'])"`
+            dut_serial=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32655_board2']['daplink'])"`
+            ./test_launcher.sh max32655 $dut_uart $dut_serial
           fi
 
       # ME14
-      - name: Check MAX32665 #name used for display purposes on github webpage
-        id: MAX32665 #id used to reference this step in other parts of the yml
+      - name: TEST MAX32665
         run: |
           # Remove local modifications
-          #git scorch
+          git scorch
 
           BLE_FILES_CHANGED=0
           RUN_TEST=0
@@ -176,17 +193,21 @@ jobs:
             RUN_TEST=1
           fi
 
-          # save result to steps output
           if [[ $RUN_TEST -eq 1 ]]
           then
-            echo "TEST_MAX32665=true" >> $GITHUB_ENV
+            echo "Running Test"   
+            cd .github/workflows/scripts
+            chmod +x test_launcher.sh
+            FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
+            dut_uart=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['uart1'])"`
+            dut_serial=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['daplink'])"`
+            ./test_launcher.sh max32665 $dut_uart $dut_serial          
           fi
       # ME18
-      - name: Check MAX32690 #name used for display purposes on github webpage
-        id: MAX32690 #id used to reference this step in other parts of the yml
+      - name: TEST MAX32690
         run: |
           # Remove local modifications
-          #git scorch
+          git scorch
 
           BLE_FILES_CHANGED=0
           RUN_TEST=0
@@ -235,66 +256,29 @@ jobs:
 
           if [[ $RUN_TEST -eq 1 ]]
           then
-            echo "TEST_MAX32690=true" >> $GITHUB_ENV
+
+            echo "Running Test"
+            
+            cd .github/workflows/scripts
+            chmod +x test_launcher.sh
+            FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
+            dut_uart=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32690_board_w1']['uart2'])"`
+            dut_serial=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32690_board_w1']['daplink'])"`            
+            ./test_launcher.sh max32690 $dut_uart $dut_serial     
           fi
 
-      - name: LOCK_BOARDS #name used for display purposes on github webpage
-        if: env.TEST_MAX32655 == 'true' || env.TEST_MAX32665 == 'true' || env.TEST_MAX32690 == 'true'
-        id: LOCK_BOARDS #id used to reference this step in other parts of the yml
-        run: |
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32655_board1
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32655_board2
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32665_board1
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32690_board_w1
-
-      - name: Test MAX32655 #name used for display purposes on github webpage
-        if: steps.LOCK_BOARDS.outcome == 'success' && env.TEST_MAX32655 == 'true'
-        id: Test_MAX32655 #id used to reference this step in other parts of the yml
-        run: |
-          echo "Running Test on MAX32655"
-          echo $env.TEST_MAX32655
-          echo $TEST_MAX32655
-
-          cd .github/workflows/scripts
-          chmod +x test_launcher.sh
-          FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
-          dut_uart=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32655_board2']['uart0'])"`
-          dut_serial=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32655_board2']['daplink'])"`
-          #./test_launcher.sh max32655 $dut_uart $dut_serial
-
-      - name: Test MAX32665 #name used for display purposes on github webpage
-        if: steps.LOCK_BOARDS.outcome == 'success' && env.TEST_MAX32665 == 'true'
-        id: Test_MAX32665 #id used to reference this step in other parts of the yml
-        run: |
-          echo "Running Test on MAX32665"
-          echo $env.TEST_MAX32665
-          echo $TEST_MAX32665
-          cd .github/workflows/scripts
-          chmod +x test_launcher.sh
-          FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
-          dut_uart=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['uart1'])"`
-          dut_serial=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['daplink'])"`
-          #./test_launcher.sh max32665 $dut_uart $dut_serial
-
-      - name: Test MAX32690 #name used for display purposes on github webpage
-        if: steps.LOCK_BOARDS.outcome == 'success' && env.TEST_MAX32690 == 'true'
-        id: Test_MAX32690 #id used to reference this step in other parts of the yml
-        run: |
-          echo "Running Test on MAX32690"
-          echo $env.TEST_MAX32690
-          echo $TEST_MAX32690
-          cd .github/workflows/scripts
-          chmod +x test_launcher.sh
-          FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
-          dut_uart=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32690_board_w1']['uart2'])"`
-          dut_serial=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32690_board_w1']['daplink'])"`
-          #./test_launcher.sh max32690 $dut_uart $dut_serial
+      # Save test reports
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: failure-report
+          path: .github/workflows/ci-tests/Examples_tests/results/
 
       # Unlock even when cancelled or failed
       # This needs some work, if the job is cancelled or times out because it could not get a LOCK
       # it then jumps here and removes all locks, that were set by a different job
       - name: Unlock All Boards
-        if: ${{ always() && steps.LOCK_BOARDS.outcome == 'success' }}
+        if: ${{ always() && steps.lock_files.outcome == 'success' }}
         run: |
           python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py max32655_board1
           python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py max32655_board2
