Using 32kHz clock for pal_timer. (#7)
* Using 32kHz clock for pal_timer.

* Accounting for short timeouts.

* Update pal_timer.c

Correcting PalTimerGetExpTime conversion.

* Increasing setup time.

* Tuning setup time.

* Updating .yml file to match msdk.

* Fixing .yml syntax.

Co-authored-by: Kevin Gillespie <Kevin.Gillespie@analog.com>

diff --git a/.github/workflows/BLE_Examples_Tests.yml b/.github/workflows/BLE_Examples_Tests.yml
--- a/.github/workflows/BLE_Examples_Tests.yml
+++ b/.github/workflows/BLE_Examples_Tests.yml
@@ -1,4 +1,4 @@
-name: BLE_Examples_Tests
+name: BLE Examples Test
 
 # Controls when the workflow will run
 on:
@@ -10,40 +10,44 @@ on:
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
-  
+
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  lock:
-    # The type of runner that the job will run on
-    runs-on: [ self-hosted, btm-ci ]
-     # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      - name: Lock Resources
-        if: ${{ always() }}
-        run: |
-          python3 /home/btm-ci/Workspace/Resource_Share/Resource_Share.py -l -t 600 /home/btm-ci/Workspace/Resource_Share/max32655_0.txt
-          python3 /home/btm-ci/Workspace/Resource_Share/Resource_Share.py -l -t 600 /home/btm-ci/Workspace/Resource_Share/max32655_1.txt
-          
   build:
     # The type of runner that the job will run on
     runs-on: [ self-hosted, btm-ci ]
-    needs: [ lock ] # Only run if the lock was successful
+
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      - name: Delete Libraries/Cordio
+      - name: Clean
+        continue-on-error: true
         run: |
-          rm -rf Libraries/Cordio
+          # Remove local modifications
+          set +e
+
+          # Attempt to clean the repo
+          git scorch
+          retval=$?
+
+          # Remove everything if this fails
+          if [[ $retval -ne 0 ]]
+          then
+            rm -rf *
+          fi
+
+          set -e
 
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
         with:
-          # Update the submodules below, doing so here will convert ssh to https
           submodules: false
+          fetch-depth: 0
           repository: Analog-Devices-MSDK/msdk
-          ref: main 
-      
+          ref: main
+
       - name: Deinit Libraries/Cordio
         run: |
+          # Remove local modifications
           git scorch
 
           # Update the submodules, this will use ssh
@@ -60,18 +64,20 @@ jobs:
 
       - name: Test BLE examples
         run: |
-          
+          # Lock hardware resources
+          python3 /home/btm-ci/Workspace/Resource_Share/Resource_Share.py -l -t 600 /home/btm-ci/Workspace/Resource_Share/max32655_0.txt
+          python3 /home/btm-ci/Workspace/Resource_Share/Resource_Share.py -l -t 600 /home/btm-ci/Workspace/Resource_Share/max32655_1.txt
           cp -r .github/workflows/ci-tests/Examples_tests .
           chmod +x Examples_tests/local_testLauncher.sh
           cd Examples_tests/
           ./local_testLauncher.sh
-          
+
       - uses: actions/upload-artifact@v3
         if: failure()
         with:
             name: failure-report
             path: Examples_tests/results/
-      
+
       # Unlock even when cancelled or failed
       - name: unlock
         if: always()
