disable old test for now

diff --git a/.github/workflows/BLE_Examples_Test.yml b/.github/workflows/BLE_Examples_Test.yml
--- a/.github/workflows/BLE_Examples_Test.yml
+++ b/.github/workflows/BLE_Examples_Test.yml
@@ -687,171 +687,171 @@ jobs:
             board_client: 'max32690_board_w1'
             board_server: 'max32655_board2'
            
-      - name: Test MAX32655 #name used for display purposes on github webpage
-        if: steps.lock_boards.outcome == 'success' && env.LOCK_MAX32655_B2 == 'true'
-        id: Test_MAX32655 #id used to reference this step in other parts of the yml
-        run: |
+    #   - name: Test MAX32655 #name used for display purposes on github webpage
+    #     if: steps.lock_boards.outcome == 'success' && env.LOCK_MAX32655_B2 == 'true'
+    #     id: Test_MAX32655 #id used to reference this step in other parts of the yml
+    #     run: |
           
 
           
-            echo
-            echo
-            echo "Examples to be tested : ${examples_to_test[@]}"
-            echo "MAX32655_RUN_ALL_TEST        : $MAX32655_RUN_ALL_TEST"
-            echo "MAX32655_DATS_CONNECTED_TEST : $MAX32655_DATS_CONNECTED_TEST "
-            echo "MAX32655_OTAS_CONNECTED_TEST  : $MAX32655_OTAS_CONNECTED_TEST"
-            echo "MAX32655_BLE_FILES_CHANGED   : $MAX32655_BLE_FILES_CHANGED "
-            echo "LOCK_MAX32655_B2             : $LOCK_MAX32655_B2 "
+    #         echo
+    #         echo
+    #         echo "Examples to be tested : ${examples_to_test[@]}"
+    #         echo "MAX32655_RUN_ALL_TEST        : $MAX32655_RUN_ALL_TEST"
+    #         echo "MAX32655_DATS_CONNECTED_TEST : $MAX32655_DATS_CONNECTED_TEST "
+    #         echo "MAX32655_OTAS_CONNECTED_TEST  : $MAX32655_OTAS_CONNECTED_TEST"
+    #         echo "MAX32655_BLE_FILES_CHANGED   : $MAX32655_BLE_FILES_CHANGED "
+    #         echo "LOCK_MAX32655_B2             : $LOCK_MAX32655_B2 "
 
-            BOARD_SERVER="max32690_board_w1"
-            BOARD_CLIENT="max32690_b1"
-            DATC_DIR=Examples/MAX32690/Bluetooth/BLE_datc
-            DATS_DIR=Examples/MAX32690/Bluetooth/BLE_dats
-            OTAS_DIR=Examples/MAX32690/Bluetooth/BLE_otas
-            OTAC_DIR=Examples/MAX32690/Bluetooth/BLE_otac
-            make -C $DATC_DIR
-            make -C $DATS_DIR
-            make -C $OTAS_DIR
-            make -C $OTAC_DIR
+    #         BOARD_SERVER="max32690_board_w1"
+    #         BOARD_CLIENT="max32690_b1"
+    #         DATC_DIR=Examples/MAX32690/Bluetooth/BLE_datc
+    #         DATS_DIR=Examples/MAX32690/Bluetooth/BLE_dats
+    #         OTAS_DIR=Examples/MAX32690/Bluetooth/BLE_otas
+    #         OTAC_DIR=Examples/MAX32690/Bluetooth/BLE_otac
+    #         make -C $DATC_DIR
+    #         make -C $DATS_DIR
+    #         make -C $OTAS_DIR
+    #         make -C $OTAC_DIR
             
-            DATS_FILE=$DATS_DIR/build/max32690.elf
-            DATC_FILE=$DATC_DIR/build/max32690.elf
-            OTAS_FILE=$OTAS_DIR/build/max32690.elf
-            OTAC_FILE=$OTAC_DIR/build/max32690.elf
+    #         DATS_FILE=$DATS_DIR/build/max32690.elf
+    #         DATC_FILE=$DATC_DIR/build/max32690.elf
+    #         OTAS_FILE=$OTAS_DIR/build/max32690.elf
+    #         OTAC_FILE=$OTAC_DIR/build/max32690.elf
           
-            echo "Testing all examples"
-            set +e
+    #         echo "Testing all examples"
+    #         set +e
     
-            connectedTests=$(datsc_connected.py $BOARD_SERVER $BOARD_CLIENT $DATS_DIR $DATC_DIR)
-            let "testResult=$?"
-            if [ "$testResult" -ne "0" ]; then
-                # update failed test count
-                let "numOfFailedTests+=$testResult"
-            fi
+    #         connectedTests=$(datsc_connected.py $BOARD_SERVER $BOARD_CLIENT $DATS_DIR $DATC_DIR)
+    #         let "testResult=$?"
+    #         if [ "$testResult" -ne "0" ]; then
+    #             # update failed test count
+    #             let "numOfFailedTests+=$testResult"
+    #         fi
 
-            otasTest=$(otas_connected.py $BOARD_SERVER $BOARD_CLIENT $OTAS_DIR $OTAC_DIR)
+    #         otasTest=$(otas_connected.py $BOARD_SERVER $BOARD_CLIENT $OTAS_DIR $OTAC_DIR)
             
-            let "testResult=$?"
-            if [ "$testResult" -ne "0" ]; then
-                # update failed test count
-                let "numOfFailedTests+=$testResult"
-            fi
-            set -e
+    #         let "testResult=$?"
+    #         if [ "$testResult" -ne "0" ]; then
+    #             # update failed test count
+    #             let "numOfFailedTests+=$testResult"
+    #         fi
+    #         set -e
 
 
 
-            echo "=============================================================================="
-            echo "=============================================================================="
+    #         echo "=============================================================================="
+    #         echo "=============================================================================="
 
-            if [[ $numOfFailedTests -ne 0 ]]; then
-                printf "Test completed with $numOfFailedTests failed tests located in: \r\n $failedTestList"
-            else
-                echo "Relax! ALL TESTS PASSED"
-            fi
-            echo
-            echo "=============================================================================="
-            echo "=============================================================================="
-            echo
+    #         if [[ $numOfFailedTests -ne 0 ]]; then
+    #             printf "Test completed with $numOfFailedTests failed tests located in: \r\n $failedTestList"
+    #         else
+    #             echo "Relax! ALL TESTS PASSED"
+    #         fi
+    #         echo
+    #         echo "=============================================================================="
+    #         echo "=============================================================================="
+    #         echo
             
 
-            exit $numOfFailedTests
-      #----------------------------------------------------------------------------------------------
-      - name: Test MAX32665 #name used for display purposes on github webpage
-        if: steps.lock_boards.outcome == 'success' && env.LOCK_MAX32665_B1 == 'true'
-        id: Test_MAX32665 #id used to reference this step in other parts of the yml
-        run: |
-          FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
-          dut_uart=$(/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['uart1'])")
-          dut_serial=$(/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['daplink'])")
-          examples_to_test=(${MAX32665_EXAMPLES_TO_TEST[@]})
-          echo
-          echo
-          echo "Examples to be tested : ${examples_to_test[@]}"
-          echo "MAX32665_RUN_ALL_TEST        : $MAX32665_RUN_ALL_TEST"
-          echo "MAX32665_DATS_CONNECTED_TEST : $MAX32665_DATS_CONNECTED_TEST "
-          echo "MAX32665_OTAS_CONNECTED_TEST  : $MAX32665_OTAS_CONNECTED_TEST"
-          echo "MAX32665_BLE_FILES_CHANGED   : $MAX32665_BLE_FILES_CHANGED "
-          echo "LOCK_MAX32665_B1             : $LOCK_MAX32665_B1 "
+    #         exit $numOfFailedTests
+    #   #----------------------------------------------------------------------------------------------
+    #   - name: Test MAX32665 #name used for display purposes on github webpage
+    #     if: steps.lock_boards.outcome == 'success' && env.LOCK_MAX32665_B1 == 'true'
+    #     id: Test_MAX32665 #id used to reference this step in other parts of the yml
+    #     run: |
+    #       FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
+    #       dut_uart=$(/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['uart1'])")
+    #       dut_serial=$(/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['daplink'])")
+    #       examples_to_test=(${MAX32665_EXAMPLES_TO_TEST[@]})
+    #       echo
+    #       echo
+    #       echo "Examples to be tested : ${examples_to_test[@]}"
+    #       echo "MAX32665_RUN_ALL_TEST        : $MAX32665_RUN_ALL_TEST"
+    #       echo "MAX32665_DATS_CONNECTED_TEST : $MAX32665_DATS_CONNECTED_TEST "
+    #       echo "MAX32665_OTAS_CONNECTED_TEST  : $MAX32665_OTAS_CONNECTED_TEST"
+    #       echo "MAX32665_BLE_FILES_CHANGED   : $MAX32665_BLE_FILES_CHANGED "
+    #       echo "LOCK_MAX32665_B1             : $LOCK_MAX32665_B1 "
 
-          cd .github/workflows/scripts
+    #       cd .github/workflows/scripts
 
-          if [[ $MAX32665_RUN_ALL_TEST == 'true' ]]; then
-              echo "Testing all examples"
-               set +e
-               ./test_launcher.sh max32665 $dut_uart $dut_serial "all"
-               let "testResult=$?"
-               if [ "$testResult" -ne "0" ]; then
-                    # update failed test count
-                    let "numOfFailedTests+=$testResult"
-                fi
-                set -e
-          else
-              if [[ $MAX32665_BLE_FILES_CHANGED == 'true' ]]; then
-                  #------non connected tests---------
-                  for example in "${examples_to_test[@]}"; do
-                      # launch single tests
-                      echo "Running $example test on MAX32665"
-                      set +e
-                      ./test_launcher.sh max32665 $dut_uart $dut_serial $example
-                      let "testResult=$?"
-                      if [ "$testResult" -ne "0" ]; then
-                          # update failed test count
-                          let "numOfFailedTests+=$testResult"
-                          failedTestList+="| $example"
-                      fi
-                      set -e
-                  done
+    #       if [[ $MAX32665_RUN_ALL_TEST == 'true' ]]; then
+    #           echo "Testing all examples"
+    #            set +e
+    #            ./test_launcher.sh max32665 $dut_uart $dut_serial "all"
+    #            let "testResult=$?"
+    #            if [ "$testResult" -ne "0" ]; then
+    #                 # update failed test count
+    #                 let "numOfFailedTests+=$testResult"
+    #             fi
+    #             set -e
+    #       else
+    #           if [[ $MAX32665_BLE_FILES_CHANGED == 'true' ]]; then
+    #               #------non connected tests---------
+    #               for example in "${examples_to_test[@]}"; do
+    #                   # launch single tests
+    #                   echo "Running $example test on MAX32665"
+    #                   set +e
+    #                   ./test_launcher.sh max32665 $dut_uart $dut_serial $example
+    #                   let "testResult=$?"
+    #                   if [ "$testResult" -ne "0" ]; then
+    #                       # update failed test count
+    #                       let "numOfFailedTests+=$testResult"
+    #                       failedTestList+="| $example"
+    #                   fi
+    #                   set -e
+    #               done
 
-                  #------connected tests---------
-                  if [[ $MAX32665_DATS_CONNECTED_TEST == 'true' ]]; then
-                      #conencted test launcher
-                      echo "Testing MAX32665_DATS_CONNECTED_TEST"
-                      set +e
-                      ./test_launcher.sh max32665 $dut_uart $dut_serial "dats"
-                      let "testResult=$?"
-                      if [ "$testResult" -ne "0" ]; then
-                          # update failed_test count
-                          let "numOfFailedTests+=$testResult"
-                          failedTestList+="| MAX32665 Dats/c"
-                      fi
-                      set -e
+    #               #------connected tests---------
+    #               if [[ $MAX32665_DATS_CONNECTED_TEST == 'true' ]]; then
+    #                   #conencted test launcher
+    #                   echo "Testing MAX32665_DATS_CONNECTED_TEST"
+    #                   set +e
+    #                   ./test_launcher.sh max32665 $dut_uart $dut_serial "dats"
+    #                   let "testResult=$?"
+    #                   if [ "$testResult" -ne "0" ]; then
+    #                       # update failed_test count
+    #                       let "numOfFailedTests+=$testResult"
+    #                       failedTestList+="| MAX32665 Dats/c"
+    #                   fi
+    #                   set -e
 
-                  fi
-                  #------connected tests---------
-                  if [[ $MAX32665_OTAS_CONNECTED_TEST == 'true' ]]; then
-                      #conencted test launcher
-                      echo "Testing MAX32665_OTAS_CONNECTED_TEST"
-                      set +e
-                      #call test here
-                      #***************** uncomment actual test here *************
-                      ./test_launcher.sh max32665 $dut_uart $dut_serial "ota"
-                      let "testResult=$?"
-                      if [ "$testResult" -ne "0" ]; then
-                          # update failed test count
-                          let "numOfFailedTests+=$testResult"
-                          failedTestList+="| MAX32665 OTAS/C"
-                      fi
-                      set -e
-                  fi
-              else
-                  echo "Skipping all tests"
-              fi
-            echo "=============================================================================="
-            echo "=============================================================================="
+    #               fi
+    #               #------connected tests---------
+    #               if [[ $MAX32665_OTAS_CONNECTED_TEST == 'true' ]]; then
+    #                   #conencted test launcher
+    #                   echo "Testing MAX32665_OTAS_CONNECTED_TEST"
+    #                   set +e
+    #                   #call test here
+    #                   #***************** uncomment actual test here *************
+    #                   ./test_launcher.sh max32665 $dut_uart $dut_serial "ota"
+    #                   let "testResult=$?"
+    #                   if [ "$testResult" -ne "0" ]; then
+    #                       # update failed test count
+    #                       let "numOfFailedTests+=$testResult"
+    #                       failedTestList+="| MAX32665 OTAS/C"
+    #                   fi
+    #                   set -e
+    #               fi
+    #           else
+    #               echo "Skipping all tests"
+    #           fi
+    #         echo "=============================================================================="
+    #         echo "=============================================================================="
 
-            if [[ $numOfFailedTests -ne 0 ]]; then
-                printf "Test completed with $numOfFailedTests failed tests located in: \r\n $failedTestList"
-            else
-                echo "Relax! ALL TESTS PASSED"
-            fi
-            echo
-            echo "=============================================================================="
-            echo "=============================================================================="
-            echo
-          fi
-          exit $numOfFailedTests
-      #----------------------------------------------------------------------------------------------
-      - name: Test MAX32690 #name used for display purposes on github webpage
+    #         if [[ $numOfFailedTests -ne 0 ]]; then
+    #             printf "Test completed with $numOfFailedTests failed tests located in: \r\n $failedTestList"
+    #         else
+    #             echo "Relax! ALL TESTS PASSED"
+    #         fi
+    #         echo
+    #         echo "=============================================================================="
+    #         echo "=============================================================================="
+    #         echo
+    #       fi
+    #       exit $numOfFailedTests
+    #   #----------------------------------------------------------------------------------------------
+    #   - name: Test MAX32690 #name used for display purposes on github webpage
         if: steps.lock_boards.outcome == 'success' && env.LOCK_MAX32690_B1 == 'true'
         id: Test_MAX32690 #id used to reference this step in other parts of the yml
         run: |
