initial

diff --git a/.github/workflows/BLE_Examples_Test.yml b/.github/workflows/BLE_Examples_Test.yml
--- a/.github/workflows/BLE_Examples_Test.yml
+++ b/.github/workflows/BLE_Examples_Test.yml
@@ -29,9 +29,10 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 env:
-  TEST_MAX32655: false
-  TEST_MAX32665: false
-  TEST_MAX32690: false
+  LOCK_MAX32655: false
+  LOCK_MAX32665: false
+  LOCK_MAX32690: false
+  # TODO WLP
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -69,237 +70,187 @@ jobs:
       # ME17
       - name: Check MAX32655 #name used for display purposes on github webpage
         id: MAX32655 #id used to reference this step in other parts of the yml
+        env:
+          MAX32655_BLE_FILES_CHANGED: false
+          MAX32655_EXAMPLES_TO_TEST: false
+          MAX32655_RUN_ALL_TEST: false
+          MAX32655_DATS_CONNETED_TEST: false
+          MAX32655_OTAS_CONNETED_TEST: false
         run: |
 
-          # Remove local modifications
-          #git scorch
-
-          BLE_FILES_CHANGED=0
-          RUN_TEST=0
-
+          declare -a watched_examples=(
+              # underscore is to ignore the BLE5_ctr examples
+              Examples/MAX32655/BLE_*
+              Examples/MAX32655/Bootloader
+          )
           # Check for changes made to these files
-          WATCH_FILES="\
-          .github/workflows/ci-tests/Examples_tests \
-          Examples/MAX32655/BLE \
-          Examples/MAX32655/Bootloader \
-          Libraries/libs.mk \
-          Libraries/Cordio \
-          Libraries/CMSIS/Device/Maxim/MAX32655 \
-          Libraries/PeriphDrivers/libPeriphDriver.mk \
-          Libraries/PeriphDrivers/periphdriver.mk \
-          Libraries/PeriphDrivers/max32655_files.mk \
-          Libraries/PeriphDrivers/Source \
-          Libraries/PeriphDrivers/Include/MAX32655 \
-          Libraries/BlePhy/MAX32655 \
-          Libraries/Boards/MAX32655"
+          # Directories to watch
+          declare -a watched_other=(
+              .github/workflows/ci-tests/Examples_tests
+              Libraries/libs.mk
+              Libraries/Cordio
+              Libraries/CMSIS/Device/Maxim/MAX32655
+              Libraries/PeriphDrivers/libPeriphDriver.mk
+              Libraries/PeriphDrivers/periphdriver.mk
+              Libraries/PeriphDrivers/max32655_files.mk
+              Libraries/PeriphDrivers/Source
+              Libraries/PeriphDrivers/Include/MAX32655
+              Libraries/BlePhy/MAX32655
+              Libraries/Boards/MAX32655)
 
-          # Get the diff from main
+          # Directories to ignore
+          declare -a ignored=(
+              Libraries/Cordio/docs
+              Documentation
+
+          )
+
+          # Create an associative array for ignored()
+          declare -A aignored=()
+          for ignore in "${ignored[@]}"; do aignored["${ignore%/}"]=1; done
+
+          # Copy the working directory list, skipping entries in ignored()
+          declare -a results_other=()
+          for watch in "${watched_other[@]}"; do test -v aignored["${watch%/}"] || results_other+=("${watch%/}"); done
+
+          # Copy the working directory list, skipping entries in ignored()
+          declare -a results_examples=()
+          for watch in "${watched_examples[@]}"; do test -v aignored["${watch%/}"] || results_examples+=("${watch%/}"); done
+
+          # Print the resulting array, separated by newlines, in sorted order
+          printf "\r\n-------- Watched Examples ------------\r\n\r\n"
+          printf '%s\n' "${results_examples[@]}" | sort
+          printf "\r\n-----------------------------------\r\n"
+
+          # Print the resulting array, separated by newlines, in sorted order
+          printf "\r\n-------- Watched Other ------------\r\n\r\n"
+          printf '%s\n' "${results_other[@]}" | sort
+          printf "\r\n-----------------------------------\r\n"
+
+          #Get the diff from main
           CHANGE_FILES=$(git diff --ignore-submodules --name-only remotes/origin/main)
-
-          echo "Watching these locations and files"
-          echo $WATCH_FILES
-
-          echo "Checking the following changes"
-          echo $CHANGE_FILES
-
           # Assume we want to actually run the workflow if no files changed
           if [[ "$CHANGE_FILES" != "" ]]; then
-            for watch_file in $WATCH_FILES; do 
-              if [[ "$CHANGE_FILES" == *"$watch_file"* ]]; then
-                BLE_FILES_CHANGED=1
-                RUN_TEST=1
-              fi
-            done
-            if [[ $BLE_FILES_CHANGED -eq 0 ]]
-            then
-              echo "Skipping MAX32655 Test"
-              # Files were changed but not in MAX32655
-              RUN_TEST=0
-            fi
-          else 
-          # Assume we want to actually run the workflow if no files changed
-            RUN_TEST=1
+              for watch_file in "${results_other[@]}"; do
+                  if [[ "$CHANGE_FILES" == *"$watch_file"* ]]; then
+                      # TODO this needs to be an env variable
+                      echo "MAX32655_RUN_ALL_TEST=true" >> $GITHUB_ENV
+                      
+                  fi
+              done
+              for watch_file in "${results_examples[@]}"; do
+                  if [[ "$CHANGE_FILES" == *"$watch_file"* ]]; then
+                      # TODO this needs to be an env variable
+                      echo "MAX32655_BLE_FILES_CHANGED=true" >> $GITHUB_ENV
+                      example_to_test=$(basename "$watch_file")
+                      # Add new element at the end of the array
+                      examples_list+=($example_to_test)
+
+                  fi
+              done
+              echo "MAX32655_EXAMPLES_TO_TEST=${examples_list[@]}" >> $GITHUB_ENV
+          else
+              # Assume we want to actually run the workflow if no files changed
+              echo "MAX32655_RUN_ALL_TEST=1" >> $GITHUB_ENV
           fi
-          # save result to steps output
-          if [[ $RUN_TEST -eq 1 ]]
-          then
-            echo "TEST_MAX32655=true" >> $GITHUB_ENV
-          fi
+          #-----------------------------------------------------------------------
 
-      # ME14
-      - name: Check MAX32665 #name used for display purposes on github webpage
-        id: MAX32665 #id used to reference this step in other parts of the yml
-        run: |
-          # Remove local modifications
-          #git scorch
-
-          BLE_FILES_CHANGED=0
-          RUN_TEST=0
-
-          # Check for changes made to these files
-          WATCH_FILES="\
-          .github/workflows/ci-tests/Examples_tests \
-          Examples/MAX32665/BLE \
-          Examples/MAX32665/Bootloader \
-          Libraries/libs.mk \
-          Libraries/Cordio \
-          Libraries/CMSIS/Device/Maxim/MAX32665 \
-          Libraries/PeriphDrivers/libPeriphDriver.mk \
-          Libraries/PeriphDrivers/periphdriver.mk \
-          Libraries/PeriphDrivers/max32665_files.mk \
-          Libraries/PeriphDrivers/Source \
-          Libraries/PeriphDrivers/Include/MAX32665 \
-          Libraries/BlePhy/MAX32665 \
-          Libraries/Boards/MAX32665"
-
-          # Get the diff from main
-          CHANGE_FILES=$(git diff --ignore-submodules --name-only remotes/origin/main)
-
-          echo "Watching these locations and files"
-          echo $WATCH_FILES
-
-          echo "Checking the following changes"
-          echo $CHANGE_FILES
-
-          # Assume we want to actually run the workflow if no files changed
-          if [[ "$CHANGE_FILES" != "" ]]; then
-            for watch_file in $WATCH_FILES; do 
-              if [[ "$CHANGE_FILES" == *"$watch_file"* ]]; then
-                BLE_FILES_CHANGED=1
-                RUN_TEST=1
-              fi
-            done
-            if [[ $BLE_FILES_CHANGED -eq 0 ]]
-            then
-              echo "Skipping MAX32665 Test"
-              # Files were changed but not in MAX32665
-              RUN_TEST=0
-            fi
-          else 
-            RUN_TEST=1
-          fi
-
-          # save result to steps output
-          if [[ $RUN_TEST -eq 1 ]]
-          then
-            echo "TEST_MAX32665=true" >> $GITHUB_ENV
-          fi
-      # ME18
-      - name: Check MAX32690 #name used for display purposes on github webpage
-        id: MAX32690 #id used to reference this step in other parts of the yml
-        run: |
-          # Remove local modifications
-          #git scorch
-
-          BLE_FILES_CHANGED=0
-          RUN_TEST=0
-          # Check for changes made to these files
-          WATCH_FILES="\
-          .github/workflows/ci-tests/Examples_tests \
-          Examples/MAX32690/BLE \
-          Examples/MAX32690/Bootloader \
-          Libraries/libs.mk \
-          Libraries/Cordio \
-          Libraries/CMSIS/Device/Maxim/MAX32690 \
-          Libraries/PeriphDrivers/libPeriphDriver.mk \
-          Libraries/PeriphDrivers/periphdriver.mk \
-          Libraries/PeriphDrivers/max32690_files.mk \
-          Libraries/PeriphDrivers/Source \
-          Libraries/PeriphDrivers/Include/MAX32690 \
-          Libraries/BlePhy/MAX32690 \
-          Libraries/Boards/MAX32690"
-
-          # Get the diff from main
-          CHANGE_FILES=$(git diff --ignore-submodules --name-only remotes/origin/main)
-
-          echo "Watching these locations and files"
-          echo $WATCH_FILES
-
-          echo "Checking the following changes"
-          echo $CHANGE_FILES
-
-          # Assume we want to actually run the workflow if no files changed
-          if [[ "$CHANGE_FILES" != "" ]]; then
-            for watch_file in $WATCH_FILES; do 
-              if [[ "$CHANGE_FILES" == *"$watch_file"* ]]; then
-                BLE_FILES_CHANGED=1
-                RUN_TEST=1
-              fi
-            done
-            if [[ $BLE_FILES_CHANGED -eq 0 ]]
-            then
-              echo "Skipping MAX32690 Test"
-              # Files were changed but not in MAX32690
-              RUN_TEST=0
-            fi
-          else 
-            RUN_TEST=1
-          fi
-
-          if [[ $RUN_TEST -eq 1 ]]
-          then
-            echo "TEST_MAX32690=true" >> $GITHUB_ENV
-          fi
-
-      - name: LOCK_BOARDS #name used for display purposes on github webpage
-        if: env.TEST_MAX32655 == 'true' || env.TEST_MAX32665 == 'true' || env.TEST_MAX32690 == 'true'
-        id: LOCK_BOARDS #id used to reference this step in other parts of the yml
+      - name: Lock MAX32655 B1
+        if: env.MAX32655_RUN_ALL_TEST == 'true' || env.MAX32655_BLE_FILES_CHANGED == 'true'
+        id: lock_max32655_b1
         run: |
           python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32655_board1
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32655_board2
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32665_board1
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py -l -t 3600 max32690_board_w1
 
       - name: Test MAX32655 #name used for display purposes on github webpage
-        if: steps.LOCK_BOARDS.outcome == 'success' && env.TEST_MAX32655 == 'true'
+        if: steps.lock_max32655_b1.outcome == 'success'
         id: Test_MAX32655 #id used to reference this step in other parts of the yml
         run: |
-          echo "Running Test on MAX32655"
-          echo $env.TEST_MAX32655
-          echo $TEST_MAX32655
-
-          cd .github/workflows/scripts
-          chmod +x test_launcher.sh
           FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
-          dut_uart=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32655_board2']['uart0'])"`
-          dut_serial=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32655_board2']['daplink'])"`
-          ./test_launcher.sh max32655 $dut_uart $dut_serial
+          dut_uart=$(/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32655_board2']['uart0'])")
+          dut_serial=$(/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32655_board2']['daplink'])")
+          echo
+          echo
+          echo "Examples to be tested : ${MAX32655_EXAMPLES_TO_TEST[@]}"
+          echo
+          echo
 
-      - name: Test MAX32665 #name used for display purposes on github webpage
-        if: steps.LOCK_BOARDS.outcome == 'success' && env.TEST_MAX32665 == 'true'
-        id: Test_MAX32665 #id used to reference this step in other parts of the yml
-        run: |
-          echo "Running Test on MAX32665"
-          echo $env.TEST_MAX32665
-          echo $TEST_MAX32665
-          cd .github/workflows/scripts
-          chmod +x test_launcher.sh
-          FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
-          dut_uart=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['uart1'])"`
-          dut_serial=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32665_board1']['daplink'])"`
-          ./test_launcher.sh max32665 $dut_uart $dut_serial
+          if [[ $MAX32655_RUN_ALL_TEST -eq 1 ]]; then
+              echo "Running ALL MAX32655 Test"
+              #***************** uncomment actual test here *************
+              #./new_test_launcher.sh max32655 $dut_uart $dut_serial "all"
+          else
+              if [[ $MAX32655_BLE_FILES_CHANGED -eq 1 ]]; then
+                  cd .github/workflows/scripts
+                  for example in "${MAX32655_EXAMPLES_TO_TEST[@]}"; do
+                      echo ">> Running $example test on MAX32655"
+                      
+                      # launch single tests
+                      set +e
+                      #***************** uncomment actual test here *************
+                      #./new_test_launcher.sh max32655 $dut_uart $dut_serial $example
+                      let "testResult=$?"
+                      if [ "$testResult" -ne "0" ]; then
+                          # update failed test count
+                          let "numOfFailedTests+=$testResult"
+                          failedTestList+="| $example"
+                      fi
+                      set -e
 
-      - name: Test MAX32690 #name used for display purposes on github webpage
-        if: steps.LOCK_BOARDS.outcome == 'success' && env.TEST_MAX32690 == 'true'
-        id: Test_MAX32690 #id used to reference this step in other parts of the yml
-        run: |
-          echo "Running Test on MAX32690"
-          echo $env.TEST_MAX32690
-          echo $TEST_MAX32690
-          cd .github/workflows/scripts
-          chmod +x test_launcher.sh
-          FILE=/home/$USER/Workspace/Resource_Share/boards_config.json
-          dut_uart=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32690_board_w1']['uart2'])"`
-          dut_serial=`/usr/bin/python3 -c "import sys, json; print(json.load(open('$FILE'))['max32690_board_w1']['daplink'])"`
-          ./test_launcher.sh max32690 $dut_uart $dut_serial
+                      # if needed enable connected state tests
+                      if [ $example == "BLE_dats" ] || [ $example == "BLE_datc" ]; then
+                          DATS_CONNETED_TEST=1
+                      fi
+                      if [ $example == "BLE_otas" ] || [ $example == "BLE_otac" ]; then
+                          OTAS_CONNETED_TEST=1
+                      fi
+                  done
 
-      # Unlock even when cancelled or failed
-      # This needs some work, if the job is cancelled or times out because it could not get a LOCK
-      # it then jumps here and removes all locks, that were set by a different job
-      - name: Unlock All Boards
-        if: ${{ always() && steps.LOCK_BOARDS.outcome == 'success' }}
+                  # connected tests
+                  if [ $DATS_CONNETED_TEST -eq 1 ]; then
+                      #conencted test launcher
+                      set +e
+                      #***************** uncomment actual test here *************
+                      #./new_test_launcher.sh max32655 $dut_uart $dut_serial "dats"
+                      let "testResult=$?"
+                      if [ "$testResult" -ne "0" ]; then
+                          # update failed_test count
+                          let "numOfFailedTests+=$testResult"
+                          failedTestList+="| MAX32655 Dats/c"
+                      fi
+                      set -e
+
+                  fi
+                  if [ $OTAS_CONNETED_TEST -eq 1 ]; then
+                      #conencted test launcher
+                      set +e
+                      #call test here
+                      #***************** uncomment actual test here *************
+                      #./new_test_launcher.sh max32655 $dut_uart $dut_serial "ota"
+                      let "testResult=$?"
+                      if [ "$testResult" -ne "0" ]; then
+                          # update failed test count
+                          let "numOfFailedTests+=$testResult"
+                          failedTestList+="| MAX32655 OTAS/C"
+                      fi
+                      set -e
+                  fi
+              else
+                  echo "Skipping all tests"
+              fi
+          fi
+
+          if [ "$numOfFailedTests" -ne "0" ]; then
+              printf "Test completed with $numOfFailedTests failed tests located in: \r\n $failedTestList"
+          else
+              echo "Relax! ALL TESTS PASSED"
+          fi
+          echo
+          echo "=============================================================================="
+          echo "=============================================================================="
+          echo
+          exit $numOfFailedTests
+
+      - name: Unlock MAX32655 B1
+        if: ${{ always() && steps.lock_max32655_b1.outcome == 'success'}}
         run: |
           python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py max32655_board1
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py max32655_board2
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py max32665_board1
-          python3 /home/$USER/Workspace/Resource_Share/Resource_Share.py max32690_board_w1
