Applying updated clean to all workflows.

diff --git a/.github/workflows/clang-format-check.yml b/.github/workflows/clang-format-check.yml
--- a/.github/workflows/clang-format-check.yml
+++ b/.github/workflows/clang-format-check.yml
@@ -26,9 +26,19 @@ jobs:
         continue-on-error: true
         run: |
           # Remove local modifications
-          set -e
-          git scorch
           set +e
+
+          # Attempt to clean the repo
+          git scorch
+          retval=$?
+
+          # Remove everything if this fails
+          if [[ $retval -ne 0 ]]
+          then
+            rm -rf *
+          fi
+
+          set -e
 
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
diff --git a/.github/workflows/clang-format-run-pr.yml b/.github/workflows/clang-format-run-pr.yml
--- a/.github/workflows/clang-format-run-pr.yml
+++ b/.github/workflows/clang-format-run-pr.yml
@@ -22,9 +22,19 @@ jobs:
       continue-on-error: true
       run: |
         # Remove local modifications
-        set -e
-        git scorch
         set +e
+
+        # Attempt to clean the repo
+        git scorch
+        retval=$?
+
+        # Remove everything if this fails
+        if [[ $retval -ne 0 ]]
+        then
+          rm -rf *
+        fi
+
+        set -e
 
     - uses: actions/github-script@v3
       id: get-pr
