Update Build_Examples.yml (#185)
* Update Build_Examples.yml

* Cleaning before checkout.

* Ignoring errors while cleaning.

* Continue on error.

* Deleting workspace if clean fails.

* Fixing error handling.

* Entering the msdk repo directory.

* printing directories.

* Not deleting entire msdk subdir.

* Applying updated clean to all workflows.

Co-authored-by: Kevin Gillespie <Kevin.Gillespie@analog.com>

diff --git a/.github/workflows/clang-format-run.yml b/.github/workflows/clang-format-run.yml
--- a/.github/workflows/clang-format-run.yml
+++ b/.github/workflows/clang-format-run.yml
@@ -19,6 +19,24 @@ jobs:
       - software
 
     steps:
+      - name: Clean
+        continue-on-error: true
+        run: |
+          # Remove local modifications
+          set +e
+
+          # Attempt to clean the repo
+          git scorch
+          retval=$?
+
+          # Remove everything if this fails
+          if [[ $retval -ne 0 ]]
+          then
+            rm -rf *
+          fi
+
+          set -e
+
       - uses: actions/checkout@v3
         with:
           submodules: false
