Deleting workspace if clean fails.

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -44,7 +44,17 @@ jobs:
         run: |
           # Remove local modifications
           set -e
+
+          # Attempt to clean the repo
           git scorch
+          retval=$?
+
+          # Remove everything if this fails
+          if [[ $retval -ne 0 ]]
+          then
+            rm -rf *
+          fi
+
           set +e
 
       ##########################
