Added per skip check and added PER test for MAX32665.

diff --git a/.github/workflows/simple_per_test.yml b/.github/workflows/simple_per_test.yml
--- a/.github/workflows/simple_per_test.yml
+++ b/.github/workflows/simple_per_test.yml
@@ -130,6 +130,21 @@ jobs:
 
         run: |
 
+          #------------------------------------------------------------------------------------------------------------
+          # Prepare the arguments for script.                    
+          MSDK=${GITHUB_WORKSPACE}
+          CHIP_UC=MAX32655
+
+          $MSDK/msdk_dev_tools/scripts/msdk_per_skip_check.sh \
+            $NO_SKIP \
+            $MSDK    \
+            $CHIP_UC
+
+          if [[ $? -ne 0 ]]; then
+            echo "SKIPPED."
+            exit 0
+          fi
+
           #------------------------------------------------
           # Prepare the arguments for function call
 
@@ -170,11 +185,95 @@ jobs:
             "${MAX32655_PHY_RA}"         \
             ${MAX32655_STEP}             \
             2>&1 | tee -a ${CURR_LOG}
-            
+          
+          if [[ $? -ne 0 ]]; then
+            exit 1
+          fi
           #------------------------------------------------          
 
       # Unlock even when cancelled or failed
       - name: unlock_max32655
+        if: always()
+        run: |
+
+          cd ${GITHUB_WORKSPACE}
+          echo PWD: `pwd`
+          echo
+
+          chmod u+x ${GITHUB_WORKSPACE}/msdk_dev_tools/scripts/unlock_plot.sh
+          ${GITHUB_WORKSPACE}/msdk_dev_tools/scripts/unlock_plot.sh ${GITHUB_WORKSPACE} ${CURR_JOB_FILE} ${all_in_one} True 2>&1 | tee -a ${CURR_LOG}
+
+
+      # Runs a set of commands using the runners shell
+      - name: max32665_simple_per_test
+        env:
+          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
+
+        run: |
+
+          #------------------------------------------------------------------------------------------------------------
+          # Prepare the arguments for script.                    
+          MSDK=${GITHUB_WORKSPACE}
+          CHIP_UC=MAX32665
+
+          $MSDK/msdk_dev_tools/scripts/msdk_per_skip_check.sh \
+            $NO_SKIP \
+            $MSDK    \
+            $CHIP_UC
+
+          if [[ $? -ne 0 ]]; then
+            echo "SKIPPED."
+            exit 0
+          fi
+
+          #------------------------------------------------
+          # Prepare the arguments for function call
+
+          if [ "${DO_MAX32665}" == "0" ]; then
+            echo "Skip the test for MAX32665."
+            exit 0
+          fi
+
+          BRD2_CHIP_LC=max32665
+
+          MSDK=${GITHUB_WORKSPACE}
+          BRD1=nRF52840_1
+          BRD2=max32665_board_w3
+
+          CURR_TIME=$(date +%Y-%m-%d_%H-%M-%S)
+
+          CURR_JOB_FILE=/home/$USER/Workspace/Resource_Share/History/msdk_simple_per_test_${CURR_TIME}_${BRD2_CHIP_LC}.txt
+          echo "::set-env name=CURR_JOB_FILE::${CURR_JOB_FILE}"
+
+          CURR_LOG=/home/$USER/Workspace/Resource_Share/Logs/msdk_simple_per_test_${CURR_TIME}_${BRD2_CHIP_LC}.log          
+          echo "::set-env name=CURR_LOG::${CURR_LOG}"
+
+          RESULT_PATH=~/Workspace/ci_results/per
+          res=${RESULT_PATH}/msdk-${CURR_TIME}
+          all_in_one=${res}_${BRD2_CHIP_LC}.csv
+          echo "::set-env name=all_in_one::${all_in_one}"
+
+          #------------------------------------------------
+          ${MSDK}/msdk_dev_tools/scripts/board_per_test.sh \
+            $MSDK      \
+            $BRD1      \
+            $BRD2      \
+            $CURR_TIME \
+            $(realpath ${CURR_JOB_FILE}) \
+            $(realpath ${CURR_LOG})      \
+            $(realpath ${all_in_one})    \
+            "${MAX32665_PKG_RA}"         \
+            "${MAX32665_PHY_RA}"         \
+            ${MAX32665_STEP}             \
+            2>&1 | tee -a ${CURR_LOG}
+          
+          if [[ $? -ne 0 ]]; then
+            exit 1
+          fi
+          #------------------------------------------------          
+
+      # Unlock even when cancelled or failed
+      - name: unlock_max32665
         if: always()
         run: |
 
